//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlkoCompanyNew.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class AlkoCompanyEntities : DbContext
    {
        public AlkoCompanyEntities()
            : base("name=AlkoCompanyEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<AnalogiGround> AnalogiGround { get; set; }
        public virtual DbSet<AnalogiHouse> AnalogiHouse { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<ObjectAssessmentAll> ObjectAssessmentAll { get; set; }
        public virtual DbSet<ObjectAssessmentGround> ObjectAssessmentGround { get; set; }
        public virtual DbSet<ObjectAssessmentHouse> ObjectAssessmentHouse { get; set; }
        public virtual DbSet<Sotrudnick> Sotrudnick { get; set; }
        public virtual DbSet<Zayavka> Zayavka { get; set; }
    }
}
