

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AlkoCompanyNew.Models.Entities
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Entities : DbContext
{
    public Entities()
        : base("name=Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AnalogiGround> AnalogiGround { get; set; }

    public virtual DbSet<AnalogiHouse> AnalogiHouse { get; set; }

    public virtual DbSet<Klient> Klient { get; set; }

    public virtual DbSet<ObjectAssessmentAll> ObjectAssessmentAll { get; set; }

    public virtual DbSet<ObjectAssessmentGround> ObjectAssessmentGround { get; set; }

    public virtual DbSet<ObjectAssessmentHouse> ObjectAssessmentHouse { get; set; }

    public virtual DbSet<Sotrudnick> Sotrudnick { get; set; }

    public virtual DbSet<SotrudnickRole> SotrudnickRole { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<Zayavka> Zayavka { get; set; }

    public virtual DbSet<ZayavkaStatus> ZayavkaStatus { get; set; }

}

}

