//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlkoCompanyNew.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalogiHouse
    {
        public int AH_ID { get; set; }
        public string AH_Adress { get; set; }
        public string AH_IstochnickInf { get; set; }
        public string AH_Contact { get; set; }
        public float AH_Ploshad { get; set; }
        public float AH_CenaProdazhiVse { get; set; }
        public float AH_CenaProdazhiKvm { get; set; }
        public float AH_KorNaUsloviaFinansirovania { get; set; }
        public float AH_KorTorg { get; set; }
        public float AH_KorNaDatuProdazhi { get; set; }
        public float AH_KorNaMesto { get; set; }
        public string AH_TypeDopPostroyki { get; set; }
        public float AH_KorNaDopPostroyki { get; set; }
        public string AH_TypeBlogoustroistva { get; set; }
        public float AH_KorNaBlagoustroistvo { get; set; }
        public string AH_Mebel { get; set; }
        public float AH_KorNaMebel { get; set; }
        public float AH_KorNaPravaZemli { get; set; }
        public float AH_KorNaMashtabZemli { get; set; }
        public float AH_KorNaPravaDom { get; set; }
        public float AH_KorNaEtage { get; set; }
        public float AH_KorNaMaterialSten { get; set; }
        public string AH_TypeOtoplenie { get; set; }
        public float AH_KorNaOtoplenie { get; set; }
        public string AH_TypeVoda { get; set; }
        public float AH_KorNaVoda { get; set; }
        public string AH_TypeCanalizacia { get; set; }
        public float AH_KorNaKanalizacia { get; set; }
        public float AH_KorNaTechSostoyanie { get; set; }
        public float AH_KorNaPloshad { get; set; }
        public string AH_TypeNarugnyuOtdelky { get; set; }
        public float AH_KorNaNarugnyuOtdelky { get; set; }
        public string AH_TypeVnutrenyuOtdelky { get; set; }
        public float AH_KorNaVnutrenyuOtdelky { get; set; }
        public byte[] AH_Photo { get; set; }
        public int OH_ID { get; set; }
    
        public virtual ObjectAssessmentHouse ObjectAssessmentHouse { get; set; }
    }
}
