
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AlkoCompanyNew.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ObjectAssessmentAll
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ObjectAssessmentAll()
    {

        this.Zayavka = new HashSet<Zayavka>();

    }


    public int OA_ID { get; set; }

    public virtual string OA_Adress { get; set; }

    public virtual Nullable<float> OA_PloshadZemli { get; set; }

    public virtual Nullable<float> OA_PloshadDom { get; set; }

    public virtual Nullable<float> OA_CenaZemliKvm { get; set; }

    public virtual Nullable<float> OA_CenaZemliVse { get; set; }

    public virtual Nullable<float> OA_CenaDomKvm { get; set; }

    public virtual Nullable<float> OA_CenaDomVse { get; set; }

    public virtual Nullable<float> OA_CenaAll { get; set; }

    public virtual Nullable<float> OA_CenaAllKvm { get; set; }

    public virtual byte[] OA_Photo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Zayavka> Zayavka { get; set; }

}

}
