//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlkoCompanyNew.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectAssessmentGround
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjectAssessmentGround()
        {
            this.AnalogiGround = new HashSet<AnalogiGround>();
        }
    
        public int OG_ID { get; set; }
        public virtual string OG_Adress { get; set; }
        public virtual string OG_KadNomer { get; set; }
        public virtual float OG_Ploshad { get; set; }
        public virtual string OG_KategoriaZemel { get; set; }
        public virtual string OG_RazreshennoeIspolzovanie { get; set; }
        public virtual float OG_CenaKvm { get; set; }
        public virtual float OG_CenaVse { get; set; }
        public virtual byte[] OG_Photo { get; set; }
        public int K_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalogiGround> AnalogiGround { get; set; }
        public virtual Klient Klient { get; set; }
    }
}
