//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlkoCompanyNew.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectAssessmentHouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjectAssessmentHouse()
        {
            this.AnalogiHouse = new HashSet<AnalogiHouse>();
            this.Zayavka = new HashSet<Zayavka>();
        }
    
        public int OH_ID { get; set; }
        public virtual string OH_Adress { get; set; }
        public virtual string OH_KadNomer { get; set; }
        public virtual Nullable<float> OH_Ploshad { get; set; }
        public virtual Nullable<float> OH_CenaKvm { get; set; }
        public virtual Nullable<float> OH_CenaVse { get; set; }
        public virtual byte[] OH_Photo { get; set; }
        public virtual string OH_DopPosroyki { get; set; }
        public virtual string OH_TypeBlogoustroistva { get; set; }
        public virtual string OH_Mebel { get; set; }
        public virtual string OH_Etagi { get; set; }
        public virtual string OH_MaterialSten { get; set; }
        public virtual string OH_Otoplenie { get; set; }
        public virtual string OH_Voda { get; set; }
        public virtual string OH_Kanalizacia { get; set; }
        public virtual string OH_FizSostoyanie { get; set; }
        public virtual string OH_NarugnayaOtdelka { get; set; }
        public virtual string OH_TypeVnutrenyuOtdelky { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalogiHouse> AnalogiHouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zayavka> Zayavka { get; set; }
    }
}
