//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlkoCompanyNew.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectAssessmentHouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjectAssessmentHouse()
        {
            this.AnalogiHouse = new HashSet<AnalogiHouse>();
        }
    
        public int OH_ID { get; set; }
        public string OH_Adress { get; set; }
        public string OH_KadNomer { get; set; }
        public float OH_Ploshad { get; set; }
        public float OH_CenaKvm { get; set; }
        public float OH_CenaVse { get; set; }
        public byte[] OH_Photo { get; set; }
        public int K_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalogiHouse> AnalogiHouse { get; set; }
        public virtual Klient Klient { get; set; }
    }
}
