//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlkoCompanyNew.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavka
    {
        public int Z_ID { get; set; }
        public string Z_Adress { get; set; }
        public string Z_Hotelka { get; set; }
        public byte[] Z_PhotoPreview { get; set; }
        public string Z_Klient { get; set; }
        public string Z_TelNumber { get; set; }
        public string Z_Primichania { get; set; }
        public string Z_Sotrudnick { get; set; }
        public string Z_DataSostavlenia { get; set; }
        public Nullable<int> S_ID { get; set; }
    }
}
